#!/bin/bash
# vim: softtabstop=2 shiftwidth=2 expandtab

## REMOTE SSH LAB

# Boot an image built by remote-ssh-build.sh in a local QEMU/KVM virtual
# machine, so remote SSH access can be exercised without a real server, and
# tear the whole thing down again afterwards.
#
# The VM is headless by default -- no display, no console -- so the only way
# in is SSH, exactly like a rented machine with no IPMI. A host port (2222 by
# default) is forwarded to the guest's dropbear on every host interface, so
# the lab is reachable both from this machine and from anywhere that can
# reach this host.

## USAGE

# Run from the same build directory used for remote-ssh-build.sh, or point
# $BUILD_DIR at it:
#
# ```
# ./remote-ssh-lab.sh              # boot; then: ssh -p 2222 root@localhost
# ./remote-ssh-lab.sh -s           # boot with a serial console attached
# ./remote-ssh-lab.sh -t 30        # override zbm.ssh_timeout for this boot
# ./remote-ssh-lab.sh -c           # just print the ssh command to use
# ./remote-ssh-lab.sh -k           # stop the running lab VM
# ./remote-ssh-lab.sh -K           # stop the VM and delete everything generated
# ```
#
# The kernel command line baked into the image by remote-ssh-build.sh
# (ip=dhcp rd.neednet=1 zbm.ssh_timeout=N) applies as-is; -t overrides only
# the timeout, which is handy for exercising the SSH wait without rebuilding.

## SCRATCH DISK

# An empty disk image is attached so ZFSBootMenu has something to scan. It
# contains no pool, so ZBM will offer to initialize and then drop into its
# recovery shell -- enough to confirm remote access works. To test a real
# boot, attach a prepared pool image with -d instead; a disk passed with -d
# is never removed by -K.

## NOTE ON DHCP

# QEMU's built-in user-mode DHCP server never sends RFC 3442 option 121, so
# this lab does not exercise the classless-static-route path. Testing that
# requires a tap device with a DHCP server configured to hand out classless
# static routes; supply it with -N.

BUILD_DIR=$(realpath "${BUILD_DIR:-${PWD}}")
RS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SSH_PORT="${SSH_PORT:-2222}"
MEMORY="${MEMORY:-2048M}"
SMP="${SMP:-2}"

RS_PIDFILE="${BUILD_DIR}/lab.pid"
RS_SCRATCH="${BUILD_DIR}/lab-scratch.img"

# Everything this script and remote-ssh-build.sh generate inside BUILD_DIR;
# anything else found there is reported rather than removed
RS_ARTIFACTS=(
  build
  dropbear
  cmdline.d
  dracut.conf.d
  dracut-modules
  sbin
  lab-scratch.img
  lab.pid
)

SERIAL=0
USE_EFI=0
TIMEOUT=""
EXTRA_DISK=""
NETDEV=""
ACTION="up"
ASSUME_YES=0

usage() {
  cat <<-EOF
	Usage: $0 [OPTIONS] [FLAGS]

	  Bring up, or tear down, a local KVM lab for a remote-ssh-build.sh image

	OPTIONS
	  -d <image>
	     Attach this disk image instead of creating a scratch disk. A disk
	     given here is never deleted by -K.

	  -N <netdev>
	     Use this qemu -netdev argument instead of user-mode networking
	     (e.g. "tap,id=n0,ifname=zbmtap0,script=no,downscript=no")

	  -p <port>
	     Forward this host port to the guest's SSH port (default: ${SSH_PORT})

	  -t <seconds>
	     Append zbm.ssh_timeout=<seconds>, overriding the image default

	FLAGS
	  -e  Boot the EFI bundle (vmlinuz.EFI) instead of kernel+initramfs

	  -s  Attach a serial console to this terminal (quit qemu with Ctrl-A X)

	  -c  Print the ssh command line for this lab and exit, without booting

	  -k  Stop a running lab VM and exit, leaving images and keys in place

	  -K  Stop the VM, then delete everything generated in the build
	      directory: images, scratch disk, dracut configuration and the
	      dropbear host keys. Prompts first unless -y is given.

	  -y  Assume "yes" for the -K confirmation prompt

	  -h  Show this message and exit
	EOF
}

# The image's dropbear host keys are regenerated by remote-ssh-build.sh
# whenever ${BUILD_DIR}/dropbear is empty, so a lab's host key legitimately
# changes from one build to the next. These options keep that out of
# ~/.ssh/known_hosts instead of asking the user to prune it by hand.
RS_SSH_OPTS=( -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR )

# Print the private key the image will actually accept, by comparing key
# fingerprints against the authorized_keys baked into the image. Nothing is
# generated here: remote-ssh-build.sh creates the dropbear HOST keys, but the
# client key is whichever of the user's keys ended up in authorized_keys.
lab_identity() {
  local _acl="${BUILD_DIR}/dropbear/authorized_keys"
  local _trusted _cand _fp

  [ -r "${_acl}" ] || return 1
  command -v ssh-keygen >/dev/null 2>&1 || return 1

  _trusted="$( ssh-keygen -lf "${_acl}" 2>/dev/null | awk '{print $2}' )"
  [ -n "${_trusted}" ] || return 1

  for _cand in "${BUILD_DIR}"/lab-key "${HOME}"/.ssh/id_*; do
    case "${_cand}" in *.pub) continue ;; esac
    [ -f "${_cand}" ] && [ -f "${_cand}.pub" ] || continue
    _fp="$( ssh-keygen -lf "${_cand}.pub" 2>/dev/null | awk '{print $2}' )"
    [ -n "${_fp}" ] || continue
    case "${_trusted}" in
      *"${_fp}"*) echo "${_cand}"; return 0 ;;
    esac
  done

  return 1
}

print_connect_info() {
  local _id _idopt=() _addrs=()

  # Absolute path, so the line works when pasted into any shell or script
  if _id="$( lab_identity )"; then
    _idopt=( -i "${_id}" )
  fi

  echo "Connect with:"
  echo
  echo "  ssh -p ${SSH_PORT} ${_idopt[*]} ${RS_SSH_OPTS[*]} root@localhost"
  echo

  if [ -z "${NETDEV}" ]; then
    while read -r _ _addr; do
      _addrs+=( "${_addr%%/*}" )
    done < <( ip -4 -o addr show scope global 2>/dev/null | awk '{print $2, $4}' )

    if [ "${#_addrs[@]}" -gt 0 ]; then
      echo "  From another machine, replace localhost with one of:"
      echo "    ${_addrs[*]}"
      echo
    fi
  fi

  if [ "${#_idopt[@]}" -eq 0 ]; then
    echo "  NOTE: no local private key matches the authorized_keys in this image;"
    echo "        add -i <key> yourself, or rebuild after putting the public key in"
    echo "        ${BUILD_DIR}/dropbear/authorized_keys"
    echo
  fi

  echo "  Host-key checking is off on purpose: the image's dropbear keys are"
  echo "  regenerated on every build, so caching them only causes warnings."
}

# PIDs of qemu processes belonging to THIS build directory. Matching on the
# build directory path keeps unrelated virtual machines on the same host --
# libvirt guests, other labs -- out of the results.
lab_pids() {
  local _proc _pid _cmd
  for _proc in /proc/[0-9]*; do
    _pid="${_proc#/proc/}"
    [ -r "${_proc}/cmdline" ] || continue
    _cmd="$( tr '\0' ' ' < "${_proc}/cmdline" 2>/dev/null )"
    case "${_cmd}" in
      *qemu-system*"${BUILD_DIR}"*) echo "${_pid}" ;;
    esac
  done
}

stop_lab() {
  local _pids _pid _waited
  _pids="$( lab_pids )"

  if [ -z "${_pids}" ]; then
    echo "No running lab VM found for ${BUILD_DIR}"
    rm -f "${RS_PIDFILE}"
    return 0
  fi

  for _pid in ${_pids}; do
    echo "Stopping lab VM (pid ${_pid})"
    kill "${_pid}" 2>/dev/null || true
  done

  # Give qemu a chance to exit before resorting to SIGKILL
  _waited=0
  while [ "${_waited}" -lt 10 ]; do
    [ -z "$( lab_pids )" ] && break
    sleep 1
    _waited=$(( _waited + 1 ))
  done

  for _pid in $( lab_pids ); do
    echo "VM (pid ${_pid}) did not exit; sending SIGKILL"
    kill -9 "${_pid}" 2>/dev/null || true
  done

  rm -f "${RS_PIDFILE}"
  return 0
}

destroy_lab() {
  local _item _present=() _leftover=() _reply _pids

  for _item in "${RS_ARTIFACTS[@]}"; do
    [ -e "${BUILD_DIR}/${_item}" ] && _present+=( "${_item}" )
  done

  _pids="$( lab_pids )"

  if [ "${#_present[@]}" -eq 0 ] && [ -z "${_pids}" ]; then
    echo "Nothing to remove in ${BUILD_DIR}, and no VM running"
    return 0
  fi

  # Nothing is stopped or deleted until the plan below is confirmed
  if [ -n "${_pids}" ]; then
    echo
    echo "About to stop the running lab VM:"
    for _item in ${_pids}; do
      echo "  pid ${_item}"
    done
  fi

  echo
  echo "About to delete from ${BUILD_DIR}:"
  for _item in "${_present[@]}"; do
    case "${_item}" in
      dropbear) echo "  ${_item}  (SSH host keys and authorized_keys)" ;;
      build) echo "  ${_item}  (kernel, initramfs and EFI bundle)" ;;
      *) echo "  ${_item}" ;;
    esac
  done

  # Anything not generated by these scripts stays; just say what is there
  while IFS= read -r _item; do
    _item="${_item#./}"
    case " ${RS_ARTIFACTS[*]} " in
      *" ${_item} "*) ;;
      *) _leftover+=( "${_item}" ) ;;
    esac
  done < <( cd "${BUILD_DIR}" && find . -maxdepth 1 -mindepth 1 -printf '%f\n' 2>/dev/null )

  if [ "${#_leftover[@]}" -gt 0 ]; then
    echo
    echo "Leaving alone (not generated by these scripts):"
    for _item in "${_leftover[@]}"; do
      echo "  ${_item}"
    done
  fi

  if ! ((ASSUME_YES)); then
    if [ ! -t 0 ]; then
      echo
      echo "ERROR: refusing to delete without confirmation; re-run with -y"
      return 1
    fi
    echo
    printf 'Proceed? [y/N] '
    read -r _reply
    case "${_reply}" in
      y|Y|yes|YES) ;;
      *) echo "Aborted; the VM is still running and nothing was deleted"; return 1 ;;
    esac
  fi

  stop_lab

  for _item in "${_present[@]}"; do
    rm -rf -- "${BUILD_DIR:?}/${_item}"
  done

  echo "Removed $(( ${#_present[@]} )) item(s) from ${BUILD_DIR}"
  echo "The build directory itself was kept; remove it with: rmdir ${BUILD_DIR}"
  echo
  echo "Not touched by this script: the zbm-builder container image"
  echo "  (remove with: podman rmi ghcr.io/zbm-dev/zbm-builder:latest)"
  echo
  echo "Nothing was written to ~/.ssh at any point, so there is no ssh"
  echo "configuration or known_hosts entry to clean up."
  return 0
}

while getopts "d:N:p:t:esckKyh" opt; do
  case "${opt}" in
    d) EXTRA_DISK="${OPTARG}" ;;
    N) NETDEV="${OPTARG}" ;;
    p) SSH_PORT="${OPTARG}" ;;
    t) TIMEOUT="${OPTARG}" ;;
    e) USE_EFI=1 ;;
    s) SERIAL=1 ;;
    c) ACTION="info" ;;
    k) ACTION="stop" ;;
    K) ACTION="destroy" ;;
    y) ASSUME_YES=1 ;;
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done

case "${ACTION}" in
  info) print_connect_info; exit $? ;;
  stop) stop_lab; exit $? ;;
  destroy) destroy_lab; exit $? ;;
esac

# zbm-builder writes its output to a "build" subdirectory of the build directory
RS_IMGDIR="${BUILD_DIR}/build"
[ -d "${RS_IMGDIR}" ] || RS_IMGDIR="${BUILD_DIR}"

if ((USE_EFI)); then
  RS_BUNDLE="${RS_IMGDIR}/vmlinuz.EFI"
  if [ ! -f "${RS_BUNDLE}" ]; then
    echo "ERROR: cannot find ${RS_BUNDLE}; run remote-ssh-build.sh first"
    exit 1
  fi

  # OVMF is needed to boot an EFI bundle; the copy in the source tree is used
  # when a system copy cannot be found
  RS_OVMF=""
  for _ovmf in "${RS_SCRIPT_DIR}/../testing/stubs/OVMF_CODE.fd" \
               /usr/share/edk2/ovmf/OVMF_CODE.fd \
               /usr/share/OVMF/OVMF_CODE.fd; do
    [ -f "${_ovmf}" ] && RS_OVMF="${_ovmf}" && break
  done

  if [ -z "${RS_OVMF}" ]; then
    echo "ERROR: cannot find OVMF firmware needed to boot an EFI bundle"
    exit 1
  fi

  BFILES=( -bios "${RS_OVMF}" -kernel "${RS_BUNDLE}" )
else
  RS_KERNEL="${RS_IMGDIR}/vmlinuz-bootmenu"
  RS_INITRD="${RS_IMGDIR}/initramfs-bootmenu.img"
  for _f in "${RS_KERNEL}" "${RS_INITRD}"; do
    if [ ! -f "${_f}" ]; then
      echo "ERROR: cannot find ${_f}; run remote-ssh-build.sh first"
      exit 1
    fi
  done

  BFILES=( -kernel "${RS_KERNEL}" -initrd "${RS_INITRD}" )
fi

# Attach the requested disk, or a scratch disk that contains no pool
if [ -n "${EXTRA_DISK}" ]; then
  if ! RS_DISK="$( realpath -e "${EXTRA_DISK}" )"; then
    echo "ERROR: disk image '${EXTRA_DISK}' does not exist"
    exit 1
  fi
else
  RS_DISK="${RS_SCRATCH}"
  if [ ! -f "${RS_DISK}" ]; then
    truncate -s 5G "${RS_DISK}" || exit 1
    echo "Created scratch disk ${RS_DISK}"
  fi
fi

# Only the kernel command line additions are set here; everything else comes
# from /etc/cmdline.d inside the image
KCL=( "loglevel=7" "zbm.show" )
[ -n "${TIMEOUT}" ] && KCL+=( "zbm.ssh_timeout=${TIMEOUT}" )

if ((SERIAL)); then
  KCL+=( "console=ttyS0,115200n8" )
  _lines="$( tput lines 2>/dev/null )"
  _cols="$( tput cols 2>/dev/null )"
  [ -n "${_lines}" ] && KCL+=( "zbm.lines=${_lines}" )
  [ -n "${_cols}" ] && KCL+=( "zbm.columns=${_cols}" )
  DISPLAY_ARGS=( -nographic )
  SERIAL_ARGS=( -serial mon:stdio )
else
  DISPLAY_ARGS=( -display none )
  SERIAL_ARGS=( )
fi

# Fall back to emulation when KVM is unavailable
if [ -w /dev/kvm ]; then
  ACCEL=( -cpu host -machine "type=q35,accel=kvm" )
else
  echo "WARNING: /dev/kvm is not writable; falling back to slow emulation"
  ACCEL=( -machine "type=q35" )
fi

if [ -n "${NETDEV}" ]; then
  NETDEV_ARG="${NETDEV}"
  NETDEV_ID="${NETDEV#*id=}"
  NETDEV_ID="${NETDEV_ID%%,*}"
else
  NETDEV_ARG="user,id=n0,hostfwd=tcp::${SSH_PORT}-:22"
  NETDEV_ID="n0"
fi

if ((SERIAL)); then
  echo "Serial console attached; quit qemu with Ctrl-A X"
else
  echo "Booting headless. SSH is the only way in."
  echo
  print_connect_info
  echo
  echo "Stop it with:    ${BASH_SOURCE[0]} -k"
  echo "Tear it down:    ${BASH_SOURCE[0]} -K"
fi

# exec replaces this shell, so qemu inherits its PID -- record it first
echo "$$" > "${RS_PIDFILE}"

exec qemu-system-x86_64 \
  "${BFILES[@]}" \
  -drive format=raw,file="${RS_DISK}" \
  -m "${MEMORY}" \
  -smp "${SMP}" \
  "${ACCEL[@]}" \
  -object rng-random,id=rng0,filename=/dev/urandom \
  -device virtio-rng-pci,rng=rng0 \
  -netdev "${NETDEV_ARG}" \
  -device virtio-net-pci,netdev="${NETDEV_ID}" \
  "${DISPLAY_ARGS[@]}" \
  "${SERIAL_ARGS[@]}" \
  -append "${KCL[*]}"
